//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace CartaDePorte.Test.servicio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="cdpSAPSoap", Namespace="http://scr.irsa.com/WebServices/")]
    public partial class cdpSAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback testDebugOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecibirPrefacturacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public cdpSAP() {
            this.Url = global::CartaDePorte.Test.Properties.Settings.Default.CartaDePorte_Test_servicio_cdpSAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event testDebugCompletedEventHandler testDebugCompleted;
        
        /// <remarks/>
        public event ProcesarClienteCompletedEventHandler ProcesarClienteCompleted;
        
        /// <remarks/>
        public event ProcesarProveedorCompletedEventHandler ProcesarProveedorCompleted;
        
        /// <remarks/>
        public event RecibirPrefacturacionCompletedEventHandler RecibirPrefacturacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scr.irsa.com/WebServices/testDebug", RequestNamespace="http://scr.irsa.com/WebServices/", ResponseNamespace="http://scr.irsa.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string testDebug() {
            object[] results = this.Invoke("testDebug", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testDebugAsync() {
            this.testDebugAsync(null);
        }
        
        /// <remarks/>
        public void testDebugAsync(object userState) {
            if ((this.testDebugOperationCompleted == null)) {
                this.testDebugOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestDebugOperationCompleted);
            }
            this.InvokeAsync("testDebug", new object[0], this.testDebugOperationCompleted, userState);
        }
        
        private void OntestDebugOperationCompleted(object arg) {
            if ((this.testDebugCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testDebugCompleted(this, new testDebugCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scr.irsa.com/WebServices/ProcesarCliente", RequestNamespace="http://scr.irsa.com/WebServices/", ResponseNamespace="http://scr.irsa.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MsgOut ProcesarCliente(ClienteXI wsCliente) {
            object[] results = this.Invoke("ProcesarCliente", new object[] {
                        wsCliente});
            return ((MsgOut)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesarClienteAsync(ClienteXI wsCliente) {
            this.ProcesarClienteAsync(wsCliente, null);
        }
        
        /// <remarks/>
        public void ProcesarClienteAsync(ClienteXI wsCliente, object userState) {
            if ((this.ProcesarClienteOperationCompleted == null)) {
                this.ProcesarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesarClienteOperationCompleted);
            }
            this.InvokeAsync("ProcesarCliente", new object[] {
                        wsCliente}, this.ProcesarClienteOperationCompleted, userState);
        }
        
        private void OnProcesarClienteOperationCompleted(object arg) {
            if ((this.ProcesarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesarClienteCompleted(this, new ProcesarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scr.irsa.com/WebServices/ProcesarProveedor", RequestNamespace="http://scr.irsa.com/WebServices/", ResponseNamespace="http://scr.irsa.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MsgOut ProcesarProveedor(ProveedorXI wsProveedor) {
            object[] results = this.Invoke("ProcesarProveedor", new object[] {
                        wsProveedor});
            return ((MsgOut)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesarProveedorAsync(ProveedorXI wsProveedor) {
            this.ProcesarProveedorAsync(wsProveedor, null);
        }
        
        /// <remarks/>
        public void ProcesarProveedorAsync(ProveedorXI wsProveedor, object userState) {
            if ((this.ProcesarProveedorOperationCompleted == null)) {
                this.ProcesarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesarProveedorOperationCompleted);
            }
            this.InvokeAsync("ProcesarProveedor", new object[] {
                        wsProveedor}, this.ProcesarProveedorOperationCompleted, userState);
        }
        
        private void OnProcesarProveedorOperationCompleted(object arg) {
            if ((this.ProcesarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesarProveedorCompleted(this, new ProcesarProveedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scr.irsa.com/WebServices/RecibirPrefacturacion", RequestNamespace="http://scr.irsa.com/WebServices/", ResponseNamespace="http://scr.irsa.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RecibirPrefacturacion(SapMensajePrefactura[] mensajes) {
            this.Invoke("RecibirPrefacturacion", new object[] {
                        mensajes});
        }
        
        /// <remarks/>
        public void RecibirPrefacturacionAsync(SapMensajePrefactura[] mensajes) {
            this.RecibirPrefacturacionAsync(mensajes, null);
        }
        
        /// <remarks/>
        public void RecibirPrefacturacionAsync(SapMensajePrefactura[] mensajes, object userState) {
            if ((this.RecibirPrefacturacionOperationCompleted == null)) {
                this.RecibirPrefacturacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirPrefacturacionOperationCompleted);
            }
            this.InvokeAsync("RecibirPrefacturacion", new object[] {
                        mensajes}, this.RecibirPrefacturacionOperationCompleted, userState);
        }
        
        private void OnRecibirPrefacturacionOperationCompleted(object arg) {
            if ((this.RecibirPrefacturacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirPrefacturacionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scr.irsa.com/WebServices/")]
    public partial class ClienteXI {
        
        private string razonSocialField;
        
        private string nombreFantasiaField;
        
        private string cUITField;
        
        private string tipoDocumentoField;
        
        private string idClienteField;
        
        private string clientePrincipalField;
        
        private string calleField;
        
        private string numeroField;
        
        private string dtoField;
        
        private string pisoField;
        
        private string cpField;
        
        private string poblacionField;
        
        private bool activoField;
        
        private string grupoComercialField;
        
        private string claveGrupoField;
        
        private string tratamientoField;
        
        private string descripcionGEField;
        
        /// <remarks/>
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        public string NombreFantasia {
            get {
                return this.nombreFantasiaField;
            }
            set {
                this.nombreFantasiaField = value;
            }
        }
        
        /// <remarks/>
        public string CUIT {
            get {
                return this.cUITField;
            }
            set {
                this.cUITField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public string ClientePrincipal {
            get {
                return this.clientePrincipalField;
            }
            set {
                this.clientePrincipalField = value;
            }
        }
        
        /// <remarks/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Dto {
            get {
                return this.dtoField;
            }
            set {
                this.dtoField = value;
            }
        }
        
        /// <remarks/>
        public string Piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
            }
        }
        
        /// <remarks/>
        public string CP {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
            }
        }
        
        /// <remarks/>
        public string Poblacion {
            get {
                return this.poblacionField;
            }
            set {
                this.poblacionField = value;
            }
        }
        
        /// <remarks/>
        public bool Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        public string GrupoComercial {
            get {
                return this.grupoComercialField;
            }
            set {
                this.grupoComercialField = value;
            }
        }
        
        /// <remarks/>
        public string ClaveGrupo {
            get {
                return this.claveGrupoField;
            }
            set {
                this.claveGrupoField = value;
            }
        }
        
        /// <remarks/>
        public string Tratamiento {
            get {
                return this.tratamientoField;
            }
            set {
                this.tratamientoField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionGE {
            get {
                return this.descripcionGEField;
            }
            set {
                this.descripcionGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scr.irsa.com/WebServices/")]
    public partial class SapMensajePrefactura {
        
        private string iDocField;
        
        private string origenField;
        
        private string nroDocumentoREField;
        
        private string nroDocumentoSapField;
        
        private string tipoMensajeField;
        
        private string textoMensajeField;
        
        /// <remarks/>
        public string IDoc {
            get {
                return this.iDocField;
            }
            set {
                this.iDocField = value;
            }
        }
        
        /// <remarks/>
        public string Origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        public string NroDocumentoRE {
            get {
                return this.nroDocumentoREField;
            }
            set {
                this.nroDocumentoREField = value;
            }
        }
        
        /// <remarks/>
        public string NroDocumentoSap {
            get {
                return this.nroDocumentoSapField;
            }
            set {
                this.nroDocumentoSapField = value;
            }
        }
        
        /// <remarks/>
        public string TipoMensaje {
            get {
                return this.tipoMensajeField;
            }
            set {
                this.tipoMensajeField = value;
            }
        }
        
        /// <remarks/>
        public string TextoMensaje {
            get {
                return this.textoMensajeField;
            }
            set {
                this.textoMensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scr.irsa.com/WebServices/")]
    public partial class ProveedorXI {
        
        private string calleField;
        
        private string pisoField;
        
        private string departamentoField;
        
        private string numeroField;
        
        private string cpField;
        
        private string ciudadField;
        
        private string paisField;
        
        private string id_ProveedorField;
        
        private string nombreField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private bool activoField;
        
        /// <remarks/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        public string Piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
            }
        }
        
        /// <remarks/>
        public string Departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string CP {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
            }
        }
        
        /// <remarks/>
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string Id_Proveedor {
            get {
                return this.id_ProveedorField;
            }
            set {
                this.id_ProveedorField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public bool Activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scr.irsa.com/WebServices/")]
    public partial class MsgOut {
        
        private int pValorField;
        
        private string pMsgField;
        
        /// <remarks/>
        public int pValor {
            get {
                return this.pValorField;
            }
            set {
                this.pValorField = value;
            }
        }
        
        /// <remarks/>
        public string pMsg {
            get {
                return this.pMsgField;
            }
            set {
                this.pMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void testDebugCompletedEventHandler(object sender, testDebugCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testDebugCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testDebugCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ProcesarClienteCompletedEventHandler(object sender, ProcesarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsgOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsgOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ProcesarProveedorCompletedEventHandler(object sender, ProcesarProveedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesarProveedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesarProveedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsgOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsgOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RecibirPrefacturacionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591