CREATE TABLE [dbo].[c1116a](
	[Idc1116a] [int] NOT NULL,
	[NroCertificadoc1116a] [nvarchar](200) NOT NULL,
	[CodigoEstablecimiento] [int] NULL,
	[CuitProveedor] [nvarchar](200) NULL,
	[RazonSocialProveedor] [nvarchar](200) NULL,
	[TipoDomicilio] [int] NULL,
	[CalleRutaProductor] [nvarchar](200) NULL,
	[NroKmProductor] [int] NULL,
	[PisoProductor] [nvarchar](50) NULL,
	[OficinaDtoProductor] [nvarchar](50) NULL,
	[CodigoLocalidadProductor] [int] NULL,
	[CodigoPartidoProductor] [int] NULL,
	[CodigoPostalProductor] [nvarchar](50) NULL,
	[CodigoEspecie] [int] NULL,
	[Cosecha] [nvarchar](50) NULL,
	[AlmacenajeDiasLibres] [int] NULL,
	[TarifaAlmacenaje] [decimal](18, 2) NULL,
	[GastoGenerales] [decimal](18, 2) NULL,
	[Zarandeo] [decimal](18, 2) NULL,
	[SecadoDe] [decimal](18, 2) NULL,
	[SecadoA] [decimal](18, 2) NULL,
	[TarifaSecado] [decimal](18, 2) NULL,
	[PuntoExceso] [decimal](18, 2) NULL,
	[TarifaOtros] [decimal](18, 2) NULL,
	[CodigoPartidoOrigen] [int] NULL,
	[CodigoPartidoEntrega] [int] NULL,
	[NumeroAnalisis] [nvarchar](200) NULL,
	[NumeroBoletin] [nvarchar](200) NULL,
	[FechaAnalisis] [datetime] NULL,
	[Grado] [nvarchar](200) NULL,
	[Factor] [decimal](18, 2) NULL,
	[ContenidoProteico] [decimal](18, 2) NULL,
	[CuitLaboratorio] [nvarchar](200) NULL,
	[NombreLaboratorio] [nvarchar](200) NULL,
	[PesoBruto] [decimal](18, 2) NULL,
	[MermaVolatil] [decimal](18, 2) NULL,
	[MermaZarandeo] [decimal](18, 2) NULL,
	[MermaSecado] [decimal](18, 2) NULL,
	[PesoNeto] [decimal](18, 2) NULL,
	[FechaCierre] [datetime] NULL,
	[ImporteIVAServicios] [decimal](18, 2) NULL,
	[TotalServicios] [decimal](18, 2) NULL,
	[NumeroCAC] [nvarchar](200) NULL,
	[UsuarioCreacion] [nvarchar](100) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioModificacion] [nvarchar](100) NULL,
	[FechaModificacion] [datetime] NULL
) ON [PRIMARY]
