CREATE TABLE [dbo].[SolicitudesRecibidas] (
    [IdSolicitudRecibida]                     INT             IDENTITY (1, 1) NOT NULL,
    [IdTipoDeCarta]                           INT             NULL,
    [NumeroCartaDePorte]                      NVARCHAR (20)   NULL,
    [Cee]                                     NVARCHAR (20)   NULL,
    [Ctg]                                     NVARCHAR (20)   NULL,
    [FechaDeEmision]                          DATETIME        NULL,
    [FechaDeCarga]                            DATETIME        NULL,
    [FechaDeVencimiento]                      DATETIME        NULL,
    [idProveedorTitularCartaDePorte]          NVARCHAR (20)   NULL,
    [IdClienteIntermediario]                  NVARCHAR (20)   NULL,
    [IdClienteRemitenteComercial]             NVARCHAR (20)   NULL,
    [RemitenteComercialComoCanjeador]         NVARCHAR (20)   NULL,
    [IdClienteCorredor]                       NVARCHAR (20)   NULL,
    [IdClienteEntregador]                     NVARCHAR (20)   NULL,
    [IdClienteDestinatario]                   NVARCHAR (20)   NULL,
    [IdClienteDestino]                        NVARCHAR (20)   NULL,
    [IdProveedorTransportista]                NVARCHAR (20)   NULL,
    [IdChofer]                                NVARCHAR (20)   NULL,
    [IdCosecha]                               INT             NULL,
    [IdEspecie]                               INT             NULL,
    [NumeroContrato]                          INT             NULL,
    [SapContrato]                             INT             NULL,
    [SinContrato]                             BIT             NULL,
    [CargaPesadaDestino]                      BIT             NULL,
    [KilogramosEstimados]                     NUMERIC (18)    NULL,
    [DeclaracionDeCalidad]                    NVARCHAR (50)   NULL,
    [IdConformeCondicional]                   INT             NULL,
    [PesoBruto]                               NUMERIC (18)    NULL,
    [PesoTara]                                NUMERIC (18)    NULL,
    [PesoNeto]                                AS              ([PesoBruto]-[PesoTara]),
    [Observaciones]                           NVARCHAR (4000) NULL,
    [LoteDeMaterial]                          NVARCHAR (50)   NULL,
    [CodigoEstablecimientoProcedencia]        NVARCHAR (15)   NULL,
    [IdLocalidadEstablecimientoProcedencia]   INT             NULL,
    [IdEstablecimientoDestino]                INT             NULL,
    [PatenteCamion]                           NVARCHAR (15)   NULL,
    [PatenteAcoplado]                         NVARCHAR (15)   NULL,
    [KmRecorridos]                            NUMERIC (18)    NULL,
    [EstadoFlete]                             INT             NULL,
    [CantHoras]                               NUMERIC (18)    NULL,
    [TarifaReferencia]                        NUMERIC (18, 2) NULL,
    [TarifaReal]                              NUMERIC (18, 2) NULL,
    [IdClientePagadorDelFlete]                INT             NULL,
    [EstadoEnSAP]                             INT             NULL,
    [EstadoEnAFIP]                            INT             NULL,
    [IdGrano]                                 INT             NULL,
    [CodigoAnulacionAfip]                     NUMERIC (18)    NULL,
    [FechaAnulacionAfip]                      DATETIME        NULL,
    [CodigoRespuestaEnvioSAP]                 NVARCHAR (50)   NULL,
    [MensajeRespuestaEnvioSAP]                NVARCHAR (500)  NULL,
    [CodigoRespuestaAnulacionSAP]             NVARCHAR (50)   NULL,
    [MensajeRespuestaAnulacionSAP]            NVARCHAR (500)  NULL,
    [CodigoEstablecimientoDestinoCambio]      NVARCHAR (15)   NULL,
    [CuitEstablecimientoDestinoCambio]        NVARCHAR (40)   NULL,
    [IdLocalidadEstablecimientoDestinoCambio] INT             NULL,
    [FechaDeDescarga]                         DATETIME        NULL,
    [FechaDeArribo]                           DATETIME        NULL,
    [PesoNetoDescarga]                        NUMERIC (18)    NULL,
    [FechaCreacion]                           DATETIME        NULL,
    [UsuarioCreacion]                         NVARCHAR (100)  NULL,
    [FechaModificacion]                       DATETIME        NULL,
    [UsuarioModificacion]                     NVARCHAR (100)  NULL,
    [IdChoferTransportista]                   INT             NULL,
	[IdEmpresa] INT NOT NULL,
    CONSTRAINT [PK_SolicitudesRecibidas] PRIMARY KEY CLUSTERED ([IdSolicitudRecibida] ASC)
);

