--CREATE TABLE [dbo].[AdminEmpresa]
--(
--	[IdEmpresa] INT            IDENTITY (1, 1) NOT NULL,
--	[Descripcion]    NVARCHAR (250) NULL,
--	[Activo]         BIT            CONSTRAINT [DF_AdminEmpresa_Activo] DEFAULT ((1)) NULL,
--	[IdGrupoEmpresa]   INT			NOT NULL, 
--	CONSTRAINT [PK_AdminEmpresa] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC)
--)
